# zk/pocgen.py — Layer 5 "Automated PoC Generator" (described Phase 4)
#
# Emits a self-contained Foundry `forge test` Solidity PoC for a CONFIRMED T4
# differential finding so the Commander can re-run the exploit end-to-end on
# any local node (anvil fork or testnet) and watch the funds move:
#
#     forge test --match-test test_exploit -vvv
#
# Built from REAL artifacts (accepted proof calldata + measured divergence),
# never hand-written placeholders. Output: VERITAS/artifacts/pocs/<label>.sol.
#
# Pitfall (learned 2026-08-18): Solidity 0.8.20 requires EIP-55 checksummed
# address literals — emitting the lowercase DB key makes the generated PoC
# fail to compile. We checksum here so the artifact is always buildable.
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


ARTIFACT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                            "artifacts", "pocs")


def _keccak256(b: bytes) -> str:
    """Keccak-256 hex (EIP-55 requirement). pycryptodome primary, eth_hash fallback."""
    try:
        from Crypto.Hash import keccak
        k = keccak.new(digest_bits=256)
        k.update(b)
        return k.hexdigest()
    except Exception:
        from eth_hash.auto import keccak as _k
        return _k(b).hex()


def _checksum(addr_hex40):
    """EIP-55 checksum an exactly-40-hex address (lowercase in, checksummed out)."""
    a = addr_hex40.lower().replace("0x", "")
    k = _keccak256(a.encode("ascii"))
    out = "".join(ch.upper() if int(k[i], 16) >= 8 else ch
                  for i, ch in enumerate(a))
    return out


def _addr_lit(a):
    a = (a or "0x").lower().replace("0x", "")
    a = a.zfill(40)                # defensive zero-pad to exact 40 hex digits
    return "0x" + _checksum(a)


def _hex_lit(data):
    """Wrap hex calldata as a Solidity `hex"..."` bytes literal."""
    h = (data or "0x").lower()
    h = h[2:] if h.startswith("0x") else h
    return f'hex"{h}"'


def _sanitize(label):
    s = re.sub(r"[^A-Za-z0-9_]", "_", str(label))
    s = re.sub(r"_+", "_", s).strip("_")
    return (s[:48] or "finding")


_POC_TEMPLATE = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title VERITAS T4/T5 PoC — {label}
/// @notice Auto-generated by zk/pocgen.py from a CONFIRMED differential hit.
///         Run: forge test --match-test test_exploit -vvv  (anvil fork / testnet)
/// @custom:malicious True
contract {label}Exploit {{
    // ---- measured artifacts (from veritas.db) ----
    address constant TARGET = {target};
    address constant ATTACKER = {attacker_addr};
    // TVL divergence observed (wei): {pre_tvl} -> {post_tvl}
    // Attacker native-ETH delta observed: {atk_delta} wei
    // Taxonomy: {taxonomy}

    /// @dev Replays the exact authorized calldata the differential loop found
    /// accepted on-chain (proof accepted, local soundness oracle False).
    /// If this tx does not revert and moves balance, the finding is
    /// financially exploitable.
    function test_exploit() external {{
        uint256 preAttacker = ATTACKER.balance;
        uint256 preTarget = TARGET.balance;

        // -- the warhead (exact calldata the target ACCEPTED) --
        (bool ok,) = TARGET.call({warhead_call});

        require(ok, "exploit tx reverted");

        uint256 atkDelta = ATTACKER.balance - preAttacker;
        uint256 tgtDelta = preTarget - TARGET.balance;

        // Divergence predicate: attacker gained OR protocol lost value.
        emit ExploitResult(ok, atkDelta, tgtDelta, {pre_tvl}, {post_tvl});
        assert(atkDelta > 0 || tgtDelta > 0);
    }}

    event ExploitResult(bool ok, uint256 atkDelta, uint256 tgtDelta,
                        uint256 preTvl, uint256 postTvl);

    receive() external payable {{}}
}}
"""


def generate_poc(target, attacker="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
                 label="finding", calldata="0x", value_wei=None,
                 pre_tvl="0", post_tvl="0", atk_delta="0",
                 taxonomy="UNCLASSIFIED", out_dir=None):
    """Emit a self-contained, CHECKSUMMED forge PoC .sol for a confirmed finding."""
    safe = _sanitize(label)
    out_dir = out_dir or ARTIFACT_DIR
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"{safe}.sol")

    if value_wei:
        # value-triggered call: TARGET.call{value: N}(<bytes>)
        warhead = f"{{value: {value_wei}}}({_hex_lit(calldata)})"
    else:
        # plain bytes call — positional, no named args
        warhead = f"({_hex_lit(calldata)})"

    src = (_POC_TEMPLATE
           .format(label=safe,
                   target=_addr_lit(target),
                   attacker_addr=_addr_lit(attacker),
                   warhead_call=warhead,
                   pre_tvl=pre_tvl, post_tvl=post_tvl,
                   atk_delta=atk_delta, taxonomy=taxonomy))
    with open(path, "w", encoding="utf-8") as f:
        f.write(src)
    return path